{% set name = "ccflow" %}
{% set version = "0.9.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/98/0a/994bf859392024b92946861552ee7d07e9790564acb6a162758be7e5afc4/ccflow-{{ version }}.tar.gz
  sha256: d6dd59b68418afa48dffce93bf884e495927bb420b9ebf804183f43b0754dc30

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - cloudpathlib
    - cloudpickle
    - dask
    - deprecated
    - hydra-core
    - ipython
    - jinja2
    - narwhals
    - numpy <3
    - orjson
    - pandas
    - pyarrow
    - pydantic >=2.6,<3
    - smart_open
    - tenacity

test:
  imports:
    - ccflow
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/point72/ccflow
  summary: 'ccflow is a collection of tools for workflow configuration, orchestration, and dependency injection'
  description: |
    ccflow is a collection of tools for workflow configuration, orchestration, and dependency injection
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ptomecek
    - timkpaine
